name: Run JUnit Tests

on:
  push:
    branches:
      - main  # Chạy khi có code mới trên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
